/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AuthError = { 'emailTaken' : null } |
  { 'wrongPassword' : null } |
  { 'blocked' : null } |
  { 'invalidInput' : string } |
  { 'notFound' : null } |
  { 'unauthorized' : null } |
  { 'suspended' : null } |
  { 'usernameTaken' : null };
export interface Breakdown {
  'humor' : bigint,
  'originality' : bigint,
  'confidence' : bigint,
}
export interface ChatMessage { 'content' : string, 'role' : string }
export interface ChatResponse {
  'coach_hint' : string,
  'coach_tone' : string,
  'feedbackCategory' : string,
  'breakdown' : Breakdown,
  'mood' : string,
  'interest_change' : bigint,
  'momentum' : string,
  'score' : bigint,
  'engagement_level' : string,
  'conversation_tension' : string,
  'updated_interest' : bigint,
  'reply' : string,
}
export interface FreePlanConfig {
  'rankedSessionsPerDay' : bigint,
  'hintsPerSession' : bigint,
  'rizzAssistPerSession' : bigint,
}
export interface PlayerStats {
  'skillTension' : bigint,
  'totalXP' : bigint,
  'skillSocialAwareness' : bigint,
  'skillHumor' : bigint,
  'sessionHistory' : Array<SessionHistoryEntry>,
  'rankId' : string,
  'skillConfidence' : bigint,
  'bestScores' : Array<[string, bigint]>,
  'skillOriginality' : bigint,
  'streakCount' : bigint,
}
export interface PublicAdminProfile {
  'id' : string,
  'username' : string,
  'createdAt' : bigint,
  'email' : string,
  'lastLogin' : bigint,
}
export interface PublicProfile {
  'id' : string,
  'status' : Status,
  'streak' : bigint,
  'username' : string,
  'totalXp' : bigint,
  'createdAt' : bigint,
  'plan' : string,
  'rank' : string,
  'email' : string,
  'unlockedChallenges' : Array<string>,
}
export interface SessionHistoryEntry {
  'isRanked' : boolean,
  'playedAt' : bigint,
  'score' : bigint,
  'challengeId' : string,
  'finalMood' : string,
  'outcome' : string,
}
export interface SessionResult {
  'rizzScore' : bigint,
  'isRanked' : boolean,
  'characterName' : string,
  'createdAt' : bigint,
  'bestMoment' : string,
  'outcomeType' : string,
  'finalMood' : string,
  'challengeType' : string,
  'areaToImprove' : string,
  'sessionId' : string,
  'xpEarned' : bigint,
  'skillsDelta' : SkillsDelta,
  'finalInterest' : bigint,
}
export interface SkillsDelta {
  'socialAwareness' : bigint,
  'humor' : bigint,
  'originality' : bigint,
  'confidence' : bigint,
  'tension' : bigint,
}
export type Status = { 'active' : null } |
  { 'blocked' : null } |
  { 'suspended' : null };
export interface _SERVICE {
  'adminLogin' : ActorMethod<
    [string, string],
    { 'ok' : { 'token' : string, 'profile' : PublicAdminProfile } } |
      { 'err' : AuthError }
  >,
  /**
   * / Admin: store the OpenAI API key (requires admin session token)
   */
  'adminLogout' : ActorMethod<[string], undefined>,
  'chat' : ActorMethod<
    [string, Array<ChatMessage>, string, string],
    ChatResponse
  >,
  'deleteUser' : ActorMethod<
    [string, string],
    { 'ok' : null } |
      { 'err' : AuthError }
  >,
  'getAdminProfile' : ActorMethod<[string], [] | [PublicAdminProfile]>,
  'getAllUsers' : ActorMethod<
    [string],
    { 'ok' : Array<PublicProfile> } |
      { 'err' : AuthError }
  >,
  'getCallerProfile' : ActorMethod<[string], [] | [PublicProfile]>,
  'getCallerSessions' : ActorMethod<[string], Array<SessionResult>>,
  'getCallerStats' : ActorMethod<[string], [] | [PlayerStats]>,
  'getCharacterState' : ActorMethod<
    [],
    {
      'age' : bigint,
      'personality' : string,
      'interest' : bigint,
      'conversation_style' : string,
      'mood' : string,
      'name' : string,
      'momentum' : string,
      'engagement_level' : string,
      'conversation_tension' : string,
    }
  >,
  'getFreePlanConfig' : ActorMethod<[], FreePlanConfig>,
  /**
   * / Frontend: query current mock mode setting
   */
  'getMockMode' : ActorMethod<[], boolean>,
  /**
   * / Authenticated query: returns the raw OpenAI API key so the frontend can
   * / call OpenAI directly (bypassing IC consensus). Requires a valid player or
   * / admin session token — unauthenticated callers get null.
   */
  'getOpenAIKey' : ActorMethod<[string], [] | [string]>,
  /**
   * / Public query: returns the raw OpenAI API key without auth.
   * / The key is the single global admin-configured key — not user-specific.
   * / This allows anonymous/guest users to use Live Mode with the admin key.
   * / Intentionally public: the key is already used client-side for all players.
   */
  'getOpenAIKeyPublic' : ActorMethod<[], [] | [string]>,
  /**
   * / Public query: returns true if an OpenAI API key has been configured, false otherwise.
   * / No auth required — knowing whether a key exists is not sensitive.
   */
  'getOpenAIKeyStatus' : ActorMethod<[], boolean>,
  'getTodayRankedSessionCount' : ActorMethod<[string], bigint>,
  'initAdmin' : ActorMethod<
    [string, string, string],
    { 'ok' : PublicAdminProfile } |
      { 'err' : AuthError }
  >,
  'isAdminToken' : ActorMethod<[string], boolean>,
  'isUsernameAvailable' : ActorMethod<[string], boolean>,
  'login' : ActorMethod<
    [string, string],
    { 'ok' : { 'token' : string, 'profile' : PublicProfile } } |
      { 'err' : AuthError }
  >,
  'logout' : ActorMethod<[string], undefined>,
  'reset' : ActorMethod<[], undefined>,
  'saveCallerProgress' : ActorMethod<
    [string, string, bigint, bigint, Array<string>],
    { 'ok' : PublicProfile } |
      { 'err' : AuthError }
  >,
  'saveCallerSession' : ActorMethod<
    [string, SessionResult],
    { 'ok' : null } |
      { 'err' : AuthError }
  >,
  'saveCallerStats' : ActorMethod<
    [string, PlayerStats],
    { 'ok' : null } |
      { 'err' : AuthError }
  >,
  'setFreePlanConfig' : ActorMethod<
    [string, FreePlanConfig],
    { 'ok' : null } |
      { 'err' : AuthError }
  >,
  /**
   * / Admin: set global mock/live mode (requires admin session token)
   */
  'setMockMode' : ActorMethod<
    [string, boolean],
    { 'ok' : null } |
      { 'err' : AuthError }
  >,
  /**
   * / Admin: store the OpenAI API key (requires admin session token)
   */
  'setOpenAIKey' : ActorMethod<
    [string, string],
    { 'ok' : null } |
      { 'err' : AuthError }
  >,
  'setUserPlan' : ActorMethod<
    [string, string, string],
    { 'ok' : null } |
      { 'err' : AuthError }
  >,
  'signup' : ActorMethod<
    [string, string, string],
    { 'ok' : PublicProfile } |
      { 'err' : AuthError }
  >,
  'transform' : ActorMethod<
    [
      {
        'context' : Uint8Array,
        'response' : {
          'status' : bigint,
          'body' : Uint8Array,
          'headers' : Array<{ 'value' : string, 'name' : string }>,
        },
      },
    ],
    {
      'status' : bigint,
      'body' : Uint8Array,
      'headers' : Array<{ 'value' : string, 'name' : string }>,
    }
  >,
  'updateUserStatus' : ActorMethod<
    [string, string, Status],
    { 'ok' : null } |
      { 'err' : AuthError }
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];