/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const PublicAdminProfile = IDL.Record({
  'id' : IDL.Text,
  'username' : IDL.Text,
  'createdAt' : IDL.Int,
  'email' : IDL.Text,
  'lastLogin' : IDL.Int,
});
export const AuthError = IDL.Variant({
  'emailTaken' : IDL.Null,
  'wrongPassword' : IDL.Null,
  'blocked' : IDL.Null,
  'invalidInput' : IDL.Text,
  'notFound' : IDL.Null,
  'unauthorized' : IDL.Null,
  'suspended' : IDL.Null,
  'usernameTaken' : IDL.Null,
});
export const ChatMessage = IDL.Record({
  'content' : IDL.Text,
  'role' : IDL.Text,
});
export const Breakdown = IDL.Record({
  'humor' : IDL.Nat,
  'originality' : IDL.Nat,
  'confidence' : IDL.Nat,
});
export const ChatResponse = IDL.Record({
  'coach_hint' : IDL.Text,
  'coach_tone' : IDL.Text,
  'feedbackCategory' : IDL.Text,
  'breakdown' : Breakdown,
  'mood' : IDL.Text,
  'interest_change' : IDL.Int,
  'momentum' : IDL.Text,
  'score' : IDL.Nat,
  'engagement_level' : IDL.Text,
  'conversation_tension' : IDL.Text,
  'updated_interest' : IDL.Int,
  'reply' : IDL.Text,
});
export const Status = IDL.Variant({
  'active' : IDL.Null,
  'blocked' : IDL.Null,
  'suspended' : IDL.Null,
});
export const PublicProfile = IDL.Record({
  'id' : IDL.Text,
  'status' : Status,
  'streak' : IDL.Nat,
  'username' : IDL.Text,
  'totalXp' : IDL.Nat,
  'createdAt' : IDL.Int,
  'plan' : IDL.Text,
  'rank' : IDL.Text,
  'email' : IDL.Text,
  'unlockedChallenges' : IDL.Vec(IDL.Text),
});
export const SkillsDelta = IDL.Record({
  'socialAwareness' : IDL.Int,
  'humor' : IDL.Int,
  'originality' : IDL.Int,
  'confidence' : IDL.Int,
  'tension' : IDL.Int,
});
export const SessionResult = IDL.Record({
  'rizzScore' : IDL.Nat,
  'isRanked' : IDL.Bool,
  'characterName' : IDL.Text,
  'createdAt' : IDL.Int,
  'bestMoment' : IDL.Text,
  'outcomeType' : IDL.Text,
  'finalMood' : IDL.Text,
  'challengeType' : IDL.Text,
  'areaToImprove' : IDL.Text,
  'sessionId' : IDL.Text,
  'xpEarned' : IDL.Nat,
  'skillsDelta' : SkillsDelta,
  'finalInterest' : IDL.Nat,
});
export const SessionHistoryEntry = IDL.Record({
  'isRanked' : IDL.Bool,
  'playedAt' : IDL.Int,
  'score' : IDL.Nat,
  'challengeId' : IDL.Text,
  'finalMood' : IDL.Text,
  'outcome' : IDL.Text,
});
export const PlayerStats = IDL.Record({
  'skillTension' : IDL.Nat,
  'totalXP' : IDL.Nat,
  'skillSocialAwareness' : IDL.Nat,
  'skillHumor' : IDL.Nat,
  'sessionHistory' : IDL.Vec(SessionHistoryEntry),
  'rankId' : IDL.Text,
  'skillConfidence' : IDL.Nat,
  'bestScores' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
  'skillOriginality' : IDL.Nat,
  'streakCount' : IDL.Nat,
});
export const FreePlanConfig = IDL.Record({
  'rankedSessionsPerDay' : IDL.Nat,
  'hintsPerSession' : IDL.Nat,
  'rizzAssistPerSession' : IDL.Nat,
});

export const idlService = IDL.Service({
  'adminLogin' : IDL.Func(
      [IDL.Text, IDL.Text],
      [
        IDL.Variant({
          'ok' : IDL.Record({
            'token' : IDL.Text,
            'profile' : PublicAdminProfile,
          }),
          'err' : AuthError,
        }),
      ],
      [],
    ),
  'adminLogout' : IDL.Func([IDL.Text], [], []),
  'chat' : IDL.Func(
      [IDL.Text, IDL.Vec(ChatMessage), IDL.Text, IDL.Text],
      [ChatResponse],
      [],
    ),
  'deleteUser' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : AuthError })],
      [],
    ),
  'getAdminProfile' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(PublicAdminProfile)],
      ['query'],
    ),
  'getAllUsers' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Vec(PublicProfile), 'err' : AuthError })],
      ['query'],
    ),
  'getCallerProfile' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(PublicProfile)],
      ['query'],
    ),
  'getCallerSessions' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(SessionResult)],
      ['query'],
    ),
  'getCallerStats' : IDL.Func([IDL.Text], [IDL.Opt(PlayerStats)], ['query']),
  'getCharacterState' : IDL.Func(
      [],
      [
        IDL.Record({
          'age' : IDL.Nat,
          'personality' : IDL.Text,
          'interest' : IDL.Int,
          'conversation_style' : IDL.Text,
          'mood' : IDL.Text,
          'name' : IDL.Text,
          'momentum' : IDL.Text,
          'engagement_level' : IDL.Text,
          'conversation_tension' : IDL.Text,
        }),
      ],
      ['query'],
    ),
  'getFreePlanConfig' : IDL.Func([], [FreePlanConfig], ['query']),
  'getMockMode' : IDL.Func([], [IDL.Bool], ['query']),
  'getOpenAIKey' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], ['query']),
  'getOpenAIKeyPublic' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
  'getOpenAIKeyStatus' : IDL.Func([], [IDL.Bool], ['query']),
  'getTodayRankedSessionCount' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
  'initAdmin' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : PublicAdminProfile, 'err' : AuthError })],
      [],
    ),
  'isAdminToken' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'isUsernameAvailable' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'login' : IDL.Func(
      [IDL.Text, IDL.Text],
      [
        IDL.Variant({
          'ok' : IDL.Record({ 'token' : IDL.Text, 'profile' : PublicProfile }),
          'err' : AuthError,
        }),
      ],
      [],
    ),
  'logout' : IDL.Func([IDL.Text], [], []),
  'reset' : IDL.Func([], [], []),
  'saveCallerProgress' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Nat, IDL.Vec(IDL.Text)],
      [IDL.Variant({ 'ok' : PublicProfile, 'err' : AuthError })],
      [],
    ),
  'saveCallerSession' : IDL.Func(
      [IDL.Text, SessionResult],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : AuthError })],
      [],
    ),
  'saveCallerStats' : IDL.Func(
      [IDL.Text, PlayerStats],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : AuthError })],
      [],
    ),
  'setFreePlanConfig' : IDL.Func(
      [IDL.Text, FreePlanConfig],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : AuthError })],
      [],
    ),
  'setMockMode' : IDL.Func(
      [IDL.Text, IDL.Bool],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : AuthError })],
      [],
    ),
  'setOpenAIKey' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : AuthError })],
      [],
    ),
  'setUserPlan' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : AuthError })],
      [],
    ),
  'signup' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : PublicProfile, 'err' : AuthError })],
      [],
    ),
  'transform' : IDL.Func(
      [
        IDL.Record({
          'context' : IDL.Vec(IDL.Nat8),
          'response' : IDL.Record({
            'status' : IDL.Nat,
            'body' : IDL.Vec(IDL.Nat8),
            'headers' : IDL.Vec(
              IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text })
            ),
          }),
        }),
      ],
      [
        IDL.Record({
          'status' : IDL.Nat,
          'body' : IDL.Vec(IDL.Nat8),
          'headers' : IDL.Vec(
            IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text })
          ),
        }),
      ],
      ['query'],
    ),
  'updateUserStatus' : IDL.Func(
      [IDL.Text, IDL.Text, Status],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : AuthError })],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const PublicAdminProfile = IDL.Record({
    'id' : IDL.Text,
    'username' : IDL.Text,
    'createdAt' : IDL.Int,
    'email' : IDL.Text,
    'lastLogin' : IDL.Int,
  });
  const AuthError = IDL.Variant({
    'emailTaken' : IDL.Null,
    'wrongPassword' : IDL.Null,
    'blocked' : IDL.Null,
    'invalidInput' : IDL.Text,
    'notFound' : IDL.Null,
    'unauthorized' : IDL.Null,
    'suspended' : IDL.Null,
    'usernameTaken' : IDL.Null,
  });
  const ChatMessage = IDL.Record({ 'content' : IDL.Text, 'role' : IDL.Text });
  const Breakdown = IDL.Record({
    'humor' : IDL.Nat,
    'originality' : IDL.Nat,
    'confidence' : IDL.Nat,
  });
  const ChatResponse = IDL.Record({
    'coach_hint' : IDL.Text,
    'coach_tone' : IDL.Text,
    'feedbackCategory' : IDL.Text,
    'breakdown' : Breakdown,
    'mood' : IDL.Text,
    'interest_change' : IDL.Int,
    'momentum' : IDL.Text,
    'score' : IDL.Nat,
    'engagement_level' : IDL.Text,
    'conversation_tension' : IDL.Text,
    'updated_interest' : IDL.Int,
    'reply' : IDL.Text,
  });
  const Status = IDL.Variant({
    'active' : IDL.Null,
    'blocked' : IDL.Null,
    'suspended' : IDL.Null,
  });
  const PublicProfile = IDL.Record({
    'id' : IDL.Text,
    'status' : Status,
    'streak' : IDL.Nat,
    'username' : IDL.Text,
    'totalXp' : IDL.Nat,
    'createdAt' : IDL.Int,
    'plan' : IDL.Text,
    'rank' : IDL.Text,
    'email' : IDL.Text,
    'unlockedChallenges' : IDL.Vec(IDL.Text),
  });
  const SkillsDelta = IDL.Record({
    'socialAwareness' : IDL.Int,
    'humor' : IDL.Int,
    'originality' : IDL.Int,
    'confidence' : IDL.Int,
    'tension' : IDL.Int,
  });
  const SessionResult = IDL.Record({
    'rizzScore' : IDL.Nat,
    'isRanked' : IDL.Bool,
    'characterName' : IDL.Text,
    'createdAt' : IDL.Int,
    'bestMoment' : IDL.Text,
    'outcomeType' : IDL.Text,
    'finalMood' : IDL.Text,
    'challengeType' : IDL.Text,
    'areaToImprove' : IDL.Text,
    'sessionId' : IDL.Text,
    'xpEarned' : IDL.Nat,
    'skillsDelta' : SkillsDelta,
    'finalInterest' : IDL.Nat,
  });
  const SessionHistoryEntry = IDL.Record({
    'isRanked' : IDL.Bool,
    'playedAt' : IDL.Int,
    'score' : IDL.Nat,
    'challengeId' : IDL.Text,
    'finalMood' : IDL.Text,
    'outcome' : IDL.Text,
  });
  const PlayerStats = IDL.Record({
    'skillTension' : IDL.Nat,
    'totalXP' : IDL.Nat,
    'skillSocialAwareness' : IDL.Nat,
    'skillHumor' : IDL.Nat,
    'sessionHistory' : IDL.Vec(SessionHistoryEntry),
    'rankId' : IDL.Text,
    'skillConfidence' : IDL.Nat,
    'bestScores' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
    'skillOriginality' : IDL.Nat,
    'streakCount' : IDL.Nat,
  });
  const FreePlanConfig = IDL.Record({
    'rankedSessionsPerDay' : IDL.Nat,
    'hintsPerSession' : IDL.Nat,
    'rizzAssistPerSession' : IDL.Nat,
  });
  
  return IDL.Service({
    'adminLogin' : IDL.Func(
        [IDL.Text, IDL.Text],
        [
          IDL.Variant({
            'ok' : IDL.Record({
              'token' : IDL.Text,
              'profile' : PublicAdminProfile,
            }),
            'err' : AuthError,
          }),
        ],
        [],
      ),
    'adminLogout' : IDL.Func([IDL.Text], [], []),
    'chat' : IDL.Func(
        [IDL.Text, IDL.Vec(ChatMessage), IDL.Text, IDL.Text],
        [ChatResponse],
        [],
      ),
    'deleteUser' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : AuthError })],
        [],
      ),
    'getAdminProfile' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(PublicAdminProfile)],
        ['query'],
      ),
    'getAllUsers' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Vec(PublicProfile), 'err' : AuthError })],
        ['query'],
      ),
    'getCallerProfile' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(PublicProfile)],
        ['query'],
      ),
    'getCallerSessions' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(SessionResult)],
        ['query'],
      ),
    'getCallerStats' : IDL.Func([IDL.Text], [IDL.Opt(PlayerStats)], ['query']),
    'getCharacterState' : IDL.Func(
        [],
        [
          IDL.Record({
            'age' : IDL.Nat,
            'personality' : IDL.Text,
            'interest' : IDL.Int,
            'conversation_style' : IDL.Text,
            'mood' : IDL.Text,
            'name' : IDL.Text,
            'momentum' : IDL.Text,
            'engagement_level' : IDL.Text,
            'conversation_tension' : IDL.Text,
          }),
        ],
        ['query'],
      ),
    'getFreePlanConfig' : IDL.Func([], [FreePlanConfig], ['query']),
    'getMockMode' : IDL.Func([], [IDL.Bool], ['query']),
    'getOpenAIKey' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], ['query']),
    'getOpenAIKeyPublic' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
    'getOpenAIKeyStatus' : IDL.Func([], [IDL.Bool], ['query']),
    'getTodayRankedSessionCount' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
    'initAdmin' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : PublicAdminProfile, 'err' : AuthError })],
        [],
      ),
    'isAdminToken' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'isUsernameAvailable' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'login' : IDL.Func(
        [IDL.Text, IDL.Text],
        [
          IDL.Variant({
            'ok' : IDL.Record({
              'token' : IDL.Text,
              'profile' : PublicProfile,
            }),
            'err' : AuthError,
          }),
        ],
        [],
      ),
    'logout' : IDL.Func([IDL.Text], [], []),
    'reset' : IDL.Func([], [], []),
    'saveCallerProgress' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Nat, IDL.Vec(IDL.Text)],
        [IDL.Variant({ 'ok' : PublicProfile, 'err' : AuthError })],
        [],
      ),
    'saveCallerSession' : IDL.Func(
        [IDL.Text, SessionResult],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : AuthError })],
        [],
      ),
    'saveCallerStats' : IDL.Func(
        [IDL.Text, PlayerStats],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : AuthError })],
        [],
      ),
    'setFreePlanConfig' : IDL.Func(
        [IDL.Text, FreePlanConfig],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : AuthError })],
        [],
      ),
    'setMockMode' : IDL.Func(
        [IDL.Text, IDL.Bool],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : AuthError })],
        [],
      ),
    'setOpenAIKey' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : AuthError })],
        [],
      ),
    'setUserPlan' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : AuthError })],
        [],
      ),
    'signup' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : PublicProfile, 'err' : AuthError })],
        [],
      ),
    'transform' : IDL.Func(
        [
          IDL.Record({
            'context' : IDL.Vec(IDL.Nat8),
            'response' : IDL.Record({
              'status' : IDL.Nat,
              'body' : IDL.Vec(IDL.Nat8),
              'headers' : IDL.Vec(
                IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text })
              ),
            }),
          }),
        ],
        [
          IDL.Record({
            'status' : IDL.Nat,
            'body' : IDL.Vec(IDL.Nat8),
            'headers' : IDL.Vec(
              IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text })
            ),
          }),
        ],
        ['query'],
      ),
    'updateUserStatus' : IDL.Func(
        [IDL.Text, IDL.Text, Status],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : AuthError })],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };