/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface SkillsDelta {
    socialAwareness: bigint;
    humor: bigint;
    originality: bigint;
    confidence: bigint;
    tension: bigint;
}
export interface SessionResult {
    rizzScore: bigint;
    isRanked: boolean;
    characterName: string;
    createdAt: bigint;
    bestMoment: string;
    outcomeType: string;
    finalMood: string;
    challengeType: string;
    areaToImprove: string;
    sessionId: string;
    xpEarned: bigint;
    skillsDelta: SkillsDelta;
    finalInterest: bigint;
}
export interface PublicProfile {
    id: string;
    status: Status;
    streak: bigint;
    username: string;
    totalXp: bigint;
    createdAt: bigint;
    plan: string;
    rank: string;
    email: string;
    unlockedChallenges: Array<string>;
}
export interface ChatResponse {
    coach_hint: string;
    coach_tone: string;
    feedbackCategory: string;
    breakdown: Breakdown;
    mood: string;
    interest_change: bigint;
    momentum: string;
    score: bigint;
    engagement_level: string;
    conversation_tension: string;
    updated_interest: bigint;
    reply: string;
}
export type AuthError = {
    __kind__: "emailTaken";
    emailTaken: null;
} | {
    __kind__: "wrongPassword";
    wrongPassword: null;
} | {
    __kind__: "blocked";
    blocked: null;
} | {
    __kind__: "invalidInput";
    invalidInput: string;
} | {
    __kind__: "notFound";
    notFound: null;
} | {
    __kind__: "unauthorized";
    unauthorized: null;
} | {
    __kind__: "suspended";
    suspended: null;
} | {
    __kind__: "usernameTaken";
    usernameTaken: null;
};
export interface FreePlanConfig {
    rankedSessionsPerDay: bigint;
    hintsPerSession: bigint;
    rizzAssistPerSession: bigint;
}
export interface ChatMessage {
    content: string;
    role: string;
}
export interface Breakdown {
    humor: bigint;
    originality: bigint;
    confidence: bigint;
}
export interface SessionHistoryEntry {
    isRanked: boolean;
    playedAt: bigint;
    score: bigint;
    challengeId: string;
    finalMood: string;
    outcome: string;
}
export interface PlayerStats {
    skillTension: bigint;
    totalXP: bigint;
    skillSocialAwareness: bigint;
    skillHumor: bigint;
    sessionHistory: Array<SessionHistoryEntry>;
    rankId: string;
    skillConfidence: bigint;
    bestScores: Array<[string, bigint]>;
    skillOriginality: bigint;
    streakCount: bigint;
}
export interface PublicAdminProfile {
    id: string;
    username: string;
    createdAt: bigint;
    email: string;
    lastLogin: bigint;
}
export enum Status {
    active = "active",
    blocked = "blocked",
    suspended = "suspended"
}
export interface backendInterface {
    adminLogin(identifier: string, password: string): Promise<{
        __kind__: "ok";
        ok: {
            token: string;
            profile: PublicAdminProfile;
        };
    } | {
        __kind__: "err";
        err: AuthError;
    }>;
    /**
     * / Admin: store the OpenAI API key (requires admin session token)
     */
    adminLogout(token: string): Promise<void>;
    chat(userMessage: string, history: Array<ChatMessage>, conversation_phase: string, character_profile_id: string): Promise<ChatResponse>;
    deleteUser(token: string, targetId: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: AuthError;
    }>;
    getAdminProfile(token: string): Promise<PublicAdminProfile | null>;
    getAllUsers(token: string): Promise<{
        __kind__: "ok";
        ok: Array<PublicProfile>;
    } | {
        __kind__: "err";
        err: AuthError;
    }>;
    getCallerProfile(token: string): Promise<PublicProfile | null>;
    getCallerSessions(token: string): Promise<Array<SessionResult>>;
    getCallerStats(token: string): Promise<PlayerStats | null>;
    getCharacterState(): Promise<{
        age: bigint;
        personality: string;
        interest: bigint;
        conversation_style: string;
        mood: string;
        name: string;
        momentum: string;
        engagement_level: string;
        conversation_tension: string;
    }>;
    getFreePlanConfig(): Promise<FreePlanConfig>;
    /**
     * / Frontend: query current mock mode setting
     */
    getMockMode(): Promise<boolean>;
    /**
     * / Authenticated query: returns the raw OpenAI API key so the frontend can
     * / call OpenAI directly (bypassing IC consensus). Requires a valid player or
     * / admin session token — unauthenticated callers get null.
     */
    getOpenAIKey(token: string): Promise<string | null>;
    /**
     * / Public query: returns the raw OpenAI API key without auth.
     * / The key is the single global admin-configured key — not user-specific.
     * / This allows anonymous/guest users to use Live Mode with the admin key.
     * / Intentionally public: the key is already used client-side for all players.
     */
    getOpenAIKeyPublic(): Promise<string | null>;
    /**
     * / Public query: returns true if an OpenAI API key has been configured, false otherwise.
     * / No auth required — knowing whether a key exists is not sensitive.
     */
    getOpenAIKeyStatus(): Promise<boolean>;
    getTodayRankedSessionCount(token: string): Promise<bigint>;
    initAdmin(username: string, email: string, password: string): Promise<{
        __kind__: "ok";
        ok: PublicAdminProfile;
    } | {
        __kind__: "err";
        err: AuthError;
    }>;
    isAdminToken(token: string): Promise<boolean>;
    isUsernameAvailable(username: string): Promise<boolean>;
    login(identifier: string, password: string): Promise<{
        __kind__: "ok";
        ok: {
            token: string;
            profile: PublicProfile;
        };
    } | {
        __kind__: "err";
        err: AuthError;
    }>;
    logout(token: string): Promise<void>;
    reset(): Promise<void>;
    saveCallerProgress(token: string, rank: string, totalXp: bigint, streak: bigint, unlockedChallenges: Array<string>): Promise<{
        __kind__: "ok";
        ok: PublicProfile;
    } | {
        __kind__: "err";
        err: AuthError;
    }>;
    saveCallerSession(token: string, session: SessionResult): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: AuthError;
    }>;
    saveCallerStats(token: string, newStats: PlayerStats): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: AuthError;
    }>;
    setFreePlanConfig(token: string, config: FreePlanConfig): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: AuthError;
    }>;
    /**
     * / Admin: set global mock/live mode (requires admin session token)
     */
    setMockMode(token: string, enabled: boolean): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: AuthError;
    }>;
    /**
     * / Admin: store the OpenAI API key (requires admin session token)
     */
    setOpenAIKey(token: string, key: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: AuthError;
    }>;
    setUserPlan(adminToken: string, userId: string, plan: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: AuthError;
    }>;
    signup(username: string, email: string, password: string): Promise<{
        __kind__: "ok";
        ok: PublicProfile;
    } | {
        __kind__: "err";
        err: AuthError;
    }>;
    transform(raw: {
        context: Uint8Array;
        response: {
            status: bigint;
            body: Uint8Array;
            headers: Array<{
                value: string;
                name: string;
            }>;
        };
    }): Promise<{
        status: bigint;
        body: Uint8Array;
        headers: Array<{
            value: string;
            name: string;
        }>;
    }>;
    updateUserStatus(token: string, targetId: string, newStatus: Status): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: AuthError;
    }>;
}
import type { AuthError as _AuthError, PlayerStats as _PlayerStats, PublicAdminProfile as _PublicAdminProfile, PublicProfile as _PublicProfile, Status as _Status } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async adminLogin(arg0: string, arg1: string): Promise<{
        __kind__: "ok";
        ok: {
            token: string;
            profile: PublicAdminProfile;
        };
    } | {
        __kind__: "err";
        err: AuthError;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.adminLogin(arg0, arg1);
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminLogin(arg0, arg1);
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminLogout(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminLogout(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminLogout(arg0);
            return result;
        }
    }
    async chat(arg0: string, arg1: Array<ChatMessage>, arg2: string, arg3: string): Promise<ChatResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.chat(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.chat(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async deleteUser(arg0: string, arg1: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: AuthError;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteUser(arg0, arg1);
                return from_candid_variant_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteUser(arg0, arg1);
            return from_candid_variant_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAdminProfile(arg0: string): Promise<PublicAdminProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminProfile(arg0);
                return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminProfile(arg0);
            return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllUsers(arg0: string): Promise<{
        __kind__: "ok";
        ok: Array<PublicProfile>;
    } | {
        __kind__: "err";
        err: AuthError;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUsers(arg0);
                return from_candid_variant_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUsers(arg0);
            return from_candid_variant_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerProfile(arg0: string): Promise<PublicProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerProfile(arg0);
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerProfile(arg0);
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerSessions(arg0: string): Promise<Array<SessionResult>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerSessions(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerSessions(arg0);
            return result;
        }
    }
    async getCallerStats(arg0: string): Promise<PlayerStats | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerStats(arg0);
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerStats(arg0);
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCharacterState(): Promise<{
        age: bigint;
        personality: string;
        interest: bigint;
        conversation_style: string;
        mood: string;
        name: string;
        momentum: string;
        engagement_level: string;
        conversation_tension: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getCharacterState();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCharacterState();
            return result;
        }
    }
    async getFreePlanConfig(): Promise<FreePlanConfig> {
        if (this.processError) {
            try {
                const result = await this.actor.getFreePlanConfig();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFreePlanConfig();
            return result;
        }
    }
    async getMockMode(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.getMockMode();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMockMode();
            return result;
        }
    }
    async getOpenAIKey(arg0: string): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getOpenAIKey(arg0);
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOpenAIKey(arg0);
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOpenAIKeyPublic(): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getOpenAIKeyPublic();
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOpenAIKeyPublic();
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOpenAIKeyStatus(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.getOpenAIKeyStatus();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOpenAIKeyStatus();
            return result;
        }
    }
    async getTodayRankedSessionCount(arg0: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getTodayRankedSessionCount(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTodayRankedSessionCount(arg0);
            return result;
        }
    }
    async initAdmin(arg0: string, arg1: string, arg2: string): Promise<{
        __kind__: "ok";
        ok: PublicAdminProfile;
    } | {
        __kind__: "err";
        err: AuthError;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.initAdmin(arg0, arg1, arg2);
                return from_candid_variant_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initAdmin(arg0, arg1, arg2);
            return from_candid_variant_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async isAdminToken(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isAdminToken(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isAdminToken(arg0);
            return result;
        }
    }
    async isUsernameAvailable(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isUsernameAvailable(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isUsernameAvailable(arg0);
            return result;
        }
    }
    async login(arg0: string, arg1: string): Promise<{
        __kind__: "ok";
        ok: {
            token: string;
            profile: PublicProfile;
        };
    } | {
        __kind__: "err";
        err: AuthError;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.login(arg0, arg1);
                return from_candid_variant_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.login(arg0, arg1);
            return from_candid_variant_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async logout(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.logout(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logout(arg0);
            return result;
        }
    }
    async reset(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.reset();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.reset();
            return result;
        }
    }
    async saveCallerProgress(arg0: string, arg1: string, arg2: bigint, arg3: bigint, arg4: Array<string>): Promise<{
        __kind__: "ok";
        ok: PublicProfile;
    } | {
        __kind__: "err";
        err: AuthError;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerProgress(arg0, arg1, arg2, arg3, arg4);
                return from_candid_variant_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerProgress(arg0, arg1, arg2, arg3, arg4);
            return from_candid_variant_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveCallerSession(arg0: string, arg1: SessionResult): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: AuthError;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerSession(arg0, arg1);
                return from_candid_variant_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerSession(arg0, arg1);
            return from_candid_variant_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveCallerStats(arg0: string, arg1: PlayerStats): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: AuthError;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerStats(arg0, arg1);
                return from_candid_variant_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerStats(arg0, arg1);
            return from_candid_variant_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async setFreePlanConfig(arg0: string, arg1: FreePlanConfig): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: AuthError;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.setFreePlanConfig(arg0, arg1);
                return from_candid_variant_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setFreePlanConfig(arg0, arg1);
            return from_candid_variant_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async setMockMode(arg0: string, arg1: boolean): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: AuthError;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.setMockMode(arg0, arg1);
                return from_candid_variant_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setMockMode(arg0, arg1);
            return from_candid_variant_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async setOpenAIKey(arg0: string, arg1: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: AuthError;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.setOpenAIKey(arg0, arg1);
                return from_candid_variant_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setOpenAIKey(arg0, arg1);
            return from_candid_variant_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async setUserPlan(arg0: string, arg1: string, arg2: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: AuthError;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.setUserPlan(arg0, arg1, arg2);
                return from_candid_variant_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setUserPlan(arg0, arg1, arg2);
            return from_candid_variant_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async signup(arg0: string, arg1: string, arg2: string): Promise<{
        __kind__: "ok";
        ok: PublicProfile;
    } | {
        __kind__: "err";
        err: AuthError;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.signup(arg0, arg1, arg2);
                return from_candid_variant_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.signup(arg0, arg1, arg2);
            return from_candid_variant_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async transform(arg0: {
        context: Uint8Array;
        response: {
            status: bigint;
            body: Uint8Array;
            headers: Array<{
                value: string;
                name: string;
            }>;
        };
    }): Promise<{
        status: bigint;
        body: Uint8Array;
        headers: Array<{
            value: string;
            name: string;
        }>;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateUserStatus(arg0: string, arg1: string, arg2: Status): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: AuthError;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUserStatus(arg0, arg1, to_candid_Status_n19(this._uploadFile, this._downloadFile, arg2));
                return from_candid_variant_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUserStatus(arg0, arg1, to_candid_Status_n19(this._uploadFile, this._downloadFile, arg2));
            return from_candid_variant_n4(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_AuthError_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AuthError): AuthError {
    return from_candid_variant_n3(_uploadFile, _downloadFile, value);
}
function from_candid_PublicProfile_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PublicProfile): PublicProfile {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_Status_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Status): Status {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PublicProfile]): PublicProfile | null {
    return value.length === 0 ? null : from_candid_PublicProfile_n8(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PlayerStats]): PlayerStats | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PublicAdminProfile]): PublicAdminProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    token: string;
    profile: _PublicProfile;
}): {
    token: string;
    profile: PublicProfile;
} {
    return {
        token: value.token,
        profile: from_candid_PublicProfile_n8(_uploadFile, _downloadFile, value.profile)
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _Status;
    streak: bigint;
    username: string;
    totalXp: bigint;
    createdAt: bigint;
    plan: string;
    rank: string;
    email: string;
    unlockedChallenges: Array<string>;
}): {
    id: string;
    status: Status;
    streak: bigint;
    username: string;
    totalXp: bigint;
    createdAt: bigint;
    plan: string;
    rank: string;
    email: string;
    unlockedChallenges: Array<string>;
} {
    return {
        id: value.id,
        status: from_candid_Status_n10(_uploadFile, _downloadFile, value.status),
        streak: value.streak,
        username: value.username,
        totalXp: value.totalXp,
        createdAt: value.createdAt,
        plan: value.plan,
        rank: value.rank,
        email: value.email,
        unlockedChallenges: value.unlockedChallenges
    };
}
function from_candid_variant_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: {
        token: string;
        profile: _PublicAdminProfile;
    };
} | {
    err: _AuthError;
}): {
    __kind__: "ok";
    ok: {
        token: string;
        profile: PublicAdminProfile;
    };
} | {
    __kind__: "err";
    err: AuthError;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_AuthError_n2(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    blocked: null;
} | {
    suspended: null;
}): Status {
    return "active" in value ? Status.active : "blocked" in value ? Status.blocked : "suspended" in value ? Status.suspended : value;
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _PublicAdminProfile;
} | {
    err: _AuthError;
}): {
    __kind__: "ok";
    ok: PublicAdminProfile;
} | {
    __kind__: "err";
    err: AuthError;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_AuthError_n2(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: {
        token: string;
        profile: _PublicProfile;
    };
} | {
    err: _AuthError;
}): {
    __kind__: "ok";
    ok: {
        token: string;
        profile: PublicProfile;
    };
} | {
    __kind__: "err";
    err: AuthError;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_record_n17(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_AuthError_n2(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _PublicProfile;
} | {
    err: _AuthError;
}): {
    __kind__: "ok";
    ok: PublicProfile;
} | {
    __kind__: "err";
    err: AuthError;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_PublicProfile_n8(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_AuthError_n2(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    emailTaken: null;
} | {
    wrongPassword: null;
} | {
    blocked: null;
} | {
    invalidInput: string;
} | {
    notFound: null;
} | {
    unauthorized: null;
} | {
    suspended: null;
} | {
    usernameTaken: null;
}): {
    __kind__: "emailTaken";
    emailTaken: null;
} | {
    __kind__: "wrongPassword";
    wrongPassword: null;
} | {
    __kind__: "blocked";
    blocked: null;
} | {
    __kind__: "invalidInput";
    invalidInput: string;
} | {
    __kind__: "notFound";
    notFound: null;
} | {
    __kind__: "unauthorized";
    unauthorized: null;
} | {
    __kind__: "suspended";
    suspended: null;
} | {
    __kind__: "usernameTaken";
    usernameTaken: null;
} {
    return "emailTaken" in value ? {
        __kind__: "emailTaken",
        emailTaken: value.emailTaken
    } : "wrongPassword" in value ? {
        __kind__: "wrongPassword",
        wrongPassword: value.wrongPassword
    } : "blocked" in value ? {
        __kind__: "blocked",
        blocked: value.blocked
    } : "invalidInput" in value ? {
        __kind__: "invalidInput",
        invalidInput: value.invalidInput
    } : "notFound" in value ? {
        __kind__: "notFound",
        notFound: value.notFound
    } : "unauthorized" in value ? {
        __kind__: "unauthorized",
        unauthorized: value.unauthorized
    } : "suspended" in value ? {
        __kind__: "suspended",
        suspended: value.suspended
    } : "usernameTaken" in value ? {
        __kind__: "usernameTaken",
        usernameTaken: value.usernameTaken
    } : value;
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: _AuthError;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: AuthError;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_AuthError_n2(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: Array<_PublicProfile>;
} | {
    err: _AuthError;
}): {
    __kind__: "ok";
    ok: Array<PublicProfile>;
} | {
    __kind__: "err";
    err: AuthError;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_vec_n7(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_AuthError_n2(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PublicProfile>): Array<PublicProfile> {
    return value.map((x)=>from_candid_PublicProfile_n8(_uploadFile, _downloadFile, x));
}
function to_candid_Status_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Status): _Status {
    return to_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Status): {
    active: null;
} | {
    blocked: null;
} | {
    suspended: null;
} {
    return value == Status.active ? {
        active: null
    } : value == Status.blocked ? {
        blocked: null
    } : value == Status.suspended ? {
        suspended: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
